INSERT INTO ROLE(ROLE_LABEL, ROLE_LEVEL) VALUES('ADMIN', 1);
INSERT INTO ROLE(ROLE_LABEL, ROLE_LEVEL) VALUES('USER', 1);
INSERT INTO API_AUTHORIZATION(API_VALUE, ROLE_ID) VALUES('post/api/admin/**', 1);
INSERT INTO API_AUTHORIZATION(API_VALUE, ROLE_ID) VALUES('get/api/**', 2);
INSERT INTO API_AUTHORIZATION(API_VALUE, ROLE_ID) VALUES('get/api/**', 1);
INSERT INTO USER(USER_LOGIN, USER_ENC_PASSWORD, USER_MAIL, USER_FIRST_NAME, USER_LAST_NAME, ROLE_ID, AUTH_TOKEN) VALUES('admin', 'admin', 'admin@admin.fr', 'admin', 'admin', 1, 'token_test');
INSERT INTO USER(USER_LOGIN, USER_ENC_PASSWORD, USER_MAIL, USER_FIRST_NAME, USER_LAST_NAME, ROLE_ID, AUTH_TOKEN) VALUES('user', 'user', 'admin@admin.fr', 'user', 'user', 2, 'token_test');
