INSERT INTO ROLE(ROLE_NAME) VALUES('ADMIN');
INSERT INTO ROLE(ROLE_NAME) VALUES('USER');
INSERT INTO USER(USER_LOGIN, USER_ENC_PASSWORD, USER_MAIL, USER_FIRST_NAME, USER_LAST_NAME, ROLE_NAME, AUTH_TOKEN) VALUES('admin', 'admin', 'admin@admin.fr', 'admin', 'admin', 'ADMIN', 'token_test');
INSERT INTO USER(USER_LOGIN, USER_ENC_PASSWORD, USER_MAIL, USER_FIRST_NAME, USER_LAST_NAME, ROLE_NAME, AUTH_TOKEN) VALUES('user', 'user', 'admin@admin.fr', 'user', 'user', 'USER', 'token_test');
